POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "To what we owe this POST",
  "author": "WomAndrew Late",
  "url": "/testblog",
  "likes": 623,
  "userId": "650d564808df9ef05f14f899"
}